apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
data:
  config.yaml: |
    server:
      port: 80
      database: "/home/filebrowser/db/database.db"
      cacheDir: "/home/filebrowser/cache"
      sources:
        - path: "/share"
          config:
            defaultEnabled: true