apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- smb-avahi-configmap.yaml
- smb-configmap.yaml
- smb-daemonset.yaml
- smb-mounthost-daemonset.yaml
- smb-namespace.yaml
- smb-pv.yaml
- smb-pvc.yaml
- smb-secrets-sealed.yaml

