apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-config
  namespace: share
data:
  # Sintassi precisa per Samba 4.x per catturare il dominio Microsoft
  user.map: |
    smbshare = "*\smbshare"
    multimedia = "*\multimedia"
    timemachine = "*\timemachine"

  smb.conf: |
    [global]
       workgroup = WORKGROUP
       interfaces = lo ovs-share
       bind interfaces only = yes
       security = user
       
       # Risolve "failed to setup guest info" forzando un utente Unix esistente
       guest account = root
       map to guest = bad user
       
       # Applica il mapping per eliminare il prefisso [MicrosoftAccount]
       username map = /etc/samba/user.map
       
       # Ottimizzazioni per Samba 4.22 Standalone
       domain master = no
       local master = no
       preferred master = no
       os level = 0

       logging = stdout
       log level = 2
       
       passdb backend = tdbsam
       
       # Estensioni macOS
       vfs objects = fruit streams_xattr
       fruit:aapl = yes
       fruit:model = MacPro7,1
       
       # Forzatura privilegi
       force user = root
       force group = root

    [Backup]
       path = /mnt/backup
       valid users = timemachine, smbshare
       writable = yes
       browsable = yes

    [Data]
       path = /mnt/data
       valid users = smbshare
       writable = yes
       browsable = yes

    [Multimedia]
       path = /mnt/multimedia
       valid users = smbshare, multimedia
       writable = yes
       browsable = yes