apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-user-script
  namespace: share
data:

  setup-users.sh: |
    #!/bin/sh
    set -e

    USERS="smbshare multimedia timemachine"

    echo "=== Creating Unix users ==="

    for USER in $USERS; do
      id "$USER" >/dev/null 2>&1 || adduser -D "$USER"
    done

    echo "=== Creating Samba users from Secret ==="

    for USER in $USERS; do

      PASS_FILE="/run/secrets/samba/$USER"

      if [ ! -f "$PASS_FILE" ]; then
        echo "Missing password secret for $USER"
        exit 1
      fi

      PASS=$(cat "$PASS_FILE")

      echo -e "$PASS\n$PASS" | smbpasswd -a -s "$USER" || true

    done

    echo "=== Samba users ready ==="