apiVersion: v1
kind: ConfigMap
metadata:
  name: avahi-config
  namespace: share
data:
  avahi-daemon.conf: |
    [server]
    # Nome che apparirà sul Finder (puoi cambiarlo a piacimento)
    host-name=marsellihomeshare
    # Fondamentale: forza Avahi a usare solo il bridge della seconda rete
    allow-interfaces=ovs-share
    use-ipv4=yes
    use-ipv6=no
    enable-dbus=no
    ratelimit-interval-usec=1000000
    ratelimit-burst=1000

    [wide-area]
    enable-wide-area=yes

    [publish]
    publish-hinfo=no
    publish-workstation=no

    [reflector]
    enable-reflector=no

    [rlimits]
    rlimit-core=0
    rlimit-data=4194304
    rlimit-fsize=0
    rlimit-nofile=768
    rlimit-stack=4194304
    rlimit-nproc=3