apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-multimedia
  namespace: share
spec:
  storageClassName: local-storage
  volumeName: pv-local-multimedia
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi